language: "ruby"

rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3.1"
  - "jruby"

sudo: false

install:
  - bundle install --retry=3

matrix:
  include:
    - rvm: "1.9"
      gemfile: "gemfiles/Gemfile.json_v1.x"
    - rvm: "2.3.1"
      gemfile: "gemfiles/Gemfile.multi_json.x"
    - rvm: "2.3.1"
      gemfile: "gemfiles/Gemfile.yajl-ruby.x"
    - rvm: "2.3.1"
      gemfile: "gemfiles/Gemfile.uuidtools.x"
